#!/usr/bin/env bash
# Emit a sorted, comparable fingerprint of a Supabase types.ts file:
# every table.column, every database function.
#
#   bash schema-fingerprint.sh <types.ts>
#
# Used to prove the VPS schema matches Lovable's live one. types.ts in the repo
# is generated by Lovable FROM the live hosted database, so it is the only
# independent witness to schema changes made through Lovable's UI that never
# landed in a migration file.
#
# Note the [a-zA-Z0-9_] character classes: table names here include digits
# (admin_i18n_templates). A [a-zA-Z_] class silently drops it and the diff
# then reports a phantom missing table.
awk '
  /^    Tables: \{/    { sec="T"; next }
  /^    Views: \{/     { sec="V"; next }
  /^    Functions: \{/ { sec="F"; next }
  /^    Enums: \{/     { sec="E"; next }
  /^    CompositeTypes: \{/ { sec="C"; next }
  sec=="T" && /^      [a-zA-Z0-9_]+: \{/ { t=$1; sub(/:$/,"",t); print "table " t; next }
  sec=="T" && /^        Row: \{/         { inrow=1; next }
  sec=="T" && inrow && /^        \}/     { inrow=0; next }
  sec=="T" && inrow && /^          [a-zA-Z0-9_]+\??:/ {
      c=$1; sub(/\??:$/,"",c); print "col   " t "." c; next }
  sec=="F" && /^      [a-zA-Z0-9_]+: \{/ { f=$1; sub(/:$/,"",f); print "func  " f; next }
' "$1" | sort -u
